<?php

/*
 * This is just a distribution file template for 'settings.inc'.
 * A copy of this file should be called 'settings.inc'. The real values of these parameters should be filled in.
 * File containing specific settings for this environment.
 * Each environment should have its own settings.inc as such, this file is listed in .gitignore
 */

const SETTINGS = [
    'database' => [
        'user' => '',
        'pass' => '',
        'host' => '',
        'db' => '',
    ],
];
